default: &default
  adapter: postgresql

development:
  <<: *default
  host: 'localhost'
  template: template0
  username: 'arthur'
  database: 'linear-ppt-development'

test:
  <<: *default
  host: localhost
  template: template0
  username: arthur
  database: linear-ppt-test

production:
  <<: *default
  host: 'localhost'
  username: 'arthur'
  database: 'linear-ppt-production'
